### PR TITLE
Resync with rodjek logrotate

### PR DESCRIPTION
**Pull request by sevaine**
Resync our fork of puppet-logrotate.  It had drifted a fair way

### CODE REVIEW

**Comment by denmat** [comment]
why don't we just pull this in from Puppetfile directly rather than maintaining our own?

**Comment by sevaine** [comment]
@denmat -- we presently do exactly that.  We may wish, at some point to make PRs against rodjek/puppet-logrotate where we need to use them in anger before they're merged into a release of the module.  In this case - I'm dusting off this fork and bringing it up to date as I may use it to create a PR to add support for managing configuration globals inside a custom /etc/logrotate.conf rather than via /etc/logrotate.d

... which is why my recent PR  in puppet land points librarian at this branch in this repo.

**Comment by denmat** [comment]
ok :+1:

**Comment by sevaine** [comment]
This has been orphaned here for a while :)  Closing it.

**Pull request closed without merging**
